name: scan_id
description: Offline document workspace for Windows and Android.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.35.7'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  file_selector: 1.0.3
  image: 4.5.4
  path: 1.9.1
  path_provider: 2.1.5
  sembast: 3.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
